### PR TITLE
Allow startServerAndCreateNextHandler to accept custom types

### PR DESCRIPTION
**Pull request by Eprince-hub**
This PR intends to solve this reported issue below
https://github.com/apollo-server-integrations/apollo-server-integration-next/issues/121

Route Handlers in Next.js 13 accept a generic type, as shown below. But this would cause a TypeScript error when being used with `startServerAndCreateNextHandler` as reported in the issue above. 

```ts
export async function POST(
  req: NextRequest,
): Promise<NextResponse<GraphQlResponseBody>>{
  return (await handler(req));
}
``` 

To solve this issue, I believe that the original type from Next.js should be returned from the line below instead of the `Response` and be allowed to accept the optional generic type
`async function handler<HandlerReq extends NextRequest | Request>(req: HandlerReq, res?: undefined): Promise<Response>;`
The above code should return the `NextResponse` type as shown below

`async function handler<HandlerReq extends NextRequest | Request>(req: HandlerReq, res?: undefined): Promise<NextResponse<ResponseBody>>;`

After this PR the `` can be used like this with no problem

```ts
// GraphQlResponseBody is a custom type depending on what my server should return
const handler = startServerAndCreateNextHandler<NextRequest, GraphQlResponseBody>(apolloServer);

// Assign the correct type to Next Route handler with no issue
export async function POST(
  req: NextRequest,
): Promise<NextResponse<GraphQlResponseBody>> {
  return await handler(req);
}
```

### CODE REVIEW

**Comment by Eprince-hub** [comment]
@martinnabhan, Thanks for running the test on this PR. I see that some prettier tests are failing, which suggests that maybe I did not run Prettier. I was wondering if I am allowed to run prettier, considering the fact that we might be using different settings. That's why I turned off prettier while working on the PR. Should I run Prettier🤔

```error
[warn] src/startServerAndCreateNextHandler.ts
[warn] Code style issues found in the above file. Forgot to run Prettier?
❌ [check:prettier] Failed with exit status 1
```

**Comment by martinnabhan** [comment]
Thank you for the pull request, and sorry for taking so long to respond!

I'm not sure if it's correct to set the handler's return type to `NextResponse<T>` because a) we actually return `Response`, not `NextResponse`, but also because b) I don't think we can meaningfully be sure what Apollo Server's response body is going to be (due to the nature of GraphQL).

What do you think @trevor-scheer?

As for prettier, I haven't added anything to the README yet about contributing but if you could make sure `npm run check` passes before requesting review it would be super helpful! If you run prettier in this repository's root directory it should use the repository's settings.

**Comment by Eprince-hub** [comment]
Thanks for the response and for taking the time to check the PR. Yes, I saw that `Response` is being returned, but I was thinking about returning the type that the `Next route` handler expects according to this merged PR https://github.com/vercel/next.js/pull/47526. The question is, if we want to stick with returning the `Response`, can it be made to accept generics? If not, the type will not conform to what the `route handler` expects and will cause the issue as reported here https://github.com/apollo-server-integrations/apollo-server-integration-next/issues/121.
Or Maybe a new type should be created and returned that accepts generics instead of returning `Response`/`NextResponse`🤔

> I don't think we can meaningfully be sure what Apollo Server's response body is going to be (due to the nature of GraphQL).

I think that using the shape of our schema, we can translate this to a TypeScript type that should be what the server should return, and this would be the `GraphQLResponseBody` that we pass to the `route handlers`, or is this not correct?

I am willing to make the necessary changes if the current solution is not optimal🙌🏼

**Comment by luchillo17** [comment]
This PR has been up for quite some time now, @Eprince-hub you still think this PR is worth it?

Not sure if it's just my use case but I see no need to type the handler return value, after all, we let go of the handler to be managed by Next, even though I do have a special use case where I create the server async...

image

**Comment by martinnabhan** [comment]
After taking another look I do believe it would be unfeasible to try to specify the return type of the handler in a meaningful way and will therefore close this pull request.

**Pull request closed without merging**
