### PR TITLE
update handler to accept optional NextResponse for nextjs 13 app rout…

### PR DESCRIPTION
**Pull request by pengyanb**
- Minor update to the handler signature to accept an optional NextResponse parameter. 
- Minor update to README.md file, to demonstrate how cookies can be added to the res object in the "graphql resolver".

### CODE REVIEW

**Comment by trevor-scheer** [comment]
@martinnabhan would you mind taking a look at this one?

**Comment by martinnabhan** [comment]
I'm not sure how I feel about passing a `NextResponse` to the context just for the sake of copying its headers (and cookies) onto the actual response? Might cause confusion when someone tries to use `res` for anything else, since `res` won't be the actual response object.

Instead I suggest we might add a `headers` property to the default context, which will have its contents copied onto the final response.

What does everyone think?

**Comment by luchillo17** [comment]
This PR has been stuck for over 6 months, and is outdated against the latest version and all, @pengyanb do you think you can check the latest version and see if this PR is still valid?

**Comment by martinnabhan** [comment]
Closing due to inactivity.

**Pull request closed without merging**
